require('plugins.packer')
require('plugins.nvimtree')
require('plugins.autopairs')
require('plugins.blankline')
require('plugins.colorizer')
require('plugins.colorscheme')
require('plugins.dashboard')
require('plugins.galaxyline')
require('plugins.gitsigns')
require('plugins.gitblame')
require('plugins.keybinds')
require('plugins.telescope')
require('plugins.toggleterm')
require('plugins.treesitter')
require('plugins.formatter')
require('plugins.hop')

